# fly.toml app configuration file generated for tankille-backend on 2023-07-10T20:09:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tankille-backend"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
